import image1 from "./assets/compact/1.png";
import image2 from "./assets/compact/2.png";
import image1h from "./assets/hotstar/1.png";
import image2h from "./assets/hotstar/2.png";
import image1e from "./assets/eclipse/1.png";

export const projectDetails = [
  {
    id: 0,
    content: `Compact Hierarchical Triples (CHT) are systems with the tertiary star orbiting the inner binary in an orbit shorter than 1000 days. 
              CHT with an eclipsing binary as its inner binary can help us extract the orbital, stellar and atmospheric properties of all the stars in the system.
               Using these parameters, I constrain the evolution of these stars and also check their future dynamical evolution.

                This work is currently funded by National Science Center (NCN), Poland through the grant no. 2021/41/N/ST9/02746 . `,
    images: [
      {
        link: image1,
        content: `Radial velocity variations of the tertiary star (boxes) vs the center-of-mass of the inner binary (triangles) of a CHT BD+442258. The green lines represent the best fit model. The veolcities are phased in time with an orbital period of 254.84 days.`,
      },
      {
        link: image2,
        content: `Best fit spectral models (orange) for the individual stars in CHT KIC06525196. The spectra was extracted from the composite spectra using spectral disentangling methods.`,
      },
    ],
  },
  {
    id: 1,
    content: `The Galactic Globular Clusters (GGCs) present in the galactic halo are old and metal-poor. This has lead to hotter populations of stars being present
              in these GGCs. These hot stars are bright in UV and belong to the evolved stages of stellar evolution, i.e, Horizontal Branch (HB), Asymptotic Giant 
              Branch (AGB) and Blue Straggler Stars (BSS). I use observations from the Ultraviolet Imaging Telescope  (link<http://www.iiap.res.in/uvit.htm><UVIT>) 
              which is onboard the space-observatory ASTROSAT and is operated by the Indian Space Research Organisation.`,
    images: [
      {
        link: image1h,
        content: `Near-UV UVIT image of hot stars in globular cluster NGC7492.`,
      },
      {
        link: image2h,
        content: `Color-magnitude diagram of stars observed in NGC 7492 using UVIT filter.`,
      },
    ],
  },
  {
    id: 2,
    content: `When there is a companion star to an eclipsing binary, the eclipses are perturbed from their periodic nature. By measuring these small perturbations, 
              we can estimate the orbits and the mass of the companion. This is done by measuring the precise time of the eclipse minima and looking for variations 
              over time. This is done with the link<http://projektsolaris.pl/en/homepage/><Solaris> (PI: Prof. M. Konacki) network of robotic telescopes which looks  
              at a large sample of eclipsing binaries. `,
    images: [
      {
        link: image1e,
        content: `Different light curves from the Solaris network of telescopes generated by my photometric pipeline.`,
      },
    ],
  },
];
